/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FondateurRouteImport } from './routes/fondateur'
import { Route as ChassisSlugRouteImport } from './routes/chassis.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FondateurRoute = FondateurRouteImport.update({
  id: '/fondateur',
  path: '/fondateur',
  getParentRoute: () => rootRouteImport,
} as any)
const ChassisSlugRoute = ChassisSlugRouteImport.update({
  id: '/chassis/$slug',
  path: '/chassis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fondateur': typeof FondateurRoute
  '/chassis/$slug': typeof ChassisSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fondateur': typeof FondateurRoute
  '/chassis/$slug': typeof ChassisSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fondateur': typeof FondateurRoute
  '/chassis/$slug': typeof ChassisSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fondateur' | '/chassis/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fondateur' | '/chassis/$slug'
  id: '__root__' | '/' | '/fondateur' | '/chassis/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FondateurRoute: typeof FondateurRoute
  ChassisSlugRoute: typeof ChassisSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fondateur': {
      id: '/fondateur'
      path: '/fondateur'
      fullPath: '/fondateur'
      preLoaderRoute: typeof FondateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chassis/$slug': {
      id: '/chassis/$slug'
      path: '/chassis/$slug'
      fullPath: '/chassis/$slug'
      preLoaderRoute: typeof ChassisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FondateurRoute: FondateurRoute,
  ChassisSlugRoute: ChassisSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
