/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BooksRouteImport } from './routes/books'
import { Route as FondateurRouteImport } from './routes/fondateur'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ChassisSlugRouteImport } from './routes/chassis.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const FondateurRoute = FondateurRouteImport.update({
  id: '/fondateur',
  path: '/fondateur',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChassisSlugRoute = ChassisSlugRouteImport.update({
  id: '/chassis/$slug',
  path: '/chassis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/fondateur': typeof FondateurRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videos': typeof VideosRoute
  '/chassis/$slug': typeof ChassisSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/fondateur': typeof FondateurRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videos': typeof VideosRoute
  '/chassis/$slug': typeof ChassisSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/fondateur': typeof FondateurRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videos': typeof VideosRoute
  '/chassis/$slug': typeof ChassisSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/books'
    | '/fondateur'
    | '/reset-password'
    | '/videos'
    | '/chassis/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/books'
    | '/fondateur'
    | '/reset-password'
    | '/videos'
    | '/chassis/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/books'
    | '/fondateur'
    | '/reset-password'
    | '/videos'
    | '/chassis/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BooksRoute: typeof BooksRoute
  FondateurRoute: typeof FondateurRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VideosRoute: typeof VideosRoute
  ChassisSlugRoute: typeof ChassisSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fondateur': {
      id: '/fondateur'
      path: '/fondateur'
      fullPath: '/fondateur'
      preLoaderRoute: typeof FondateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chassis/$slug': {
      id: '/chassis/$slug'
      path: '/chassis/$slug'
      fullPath: '/chassis/$slug'
      preLoaderRoute: typeof ChassisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BooksRoute: BooksRoute,
  FondateurRoute: FondateurRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VideosRoute: VideosRoute,
  ChassisSlugRoute: ChassisSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
